### PR TITLE
Use openmpt_modplug instead of the deprecated modplug.

### PR DESCRIPTION
**Pull request by extrowerk**
Openmpt-modplug is a drop in replacement for modplug.

### CODE REVIEW

**Comment by Brunobasta** [comment]
yes I need sound too...

**Comment by Brunobasta** [comment]
yes I need sound too...

**Comment by cyxx** [comment]
I would like to keep libmodplug as the default.

Would having a variable at the top of Makefile to override the value help for your target platform?
eg. `MODPLUG_LIBS ?= -lmodplug`

**Comment by Brunobasta** [comment]
It works ok with full game

**Comment by cyxx** [comment]
Merged.
Library can be overridden with `MODPLUG_LIBS=openmpt_modplug make`

**Pull request closed without merging**
