### PR TITLE
Misc improvements for Prehistorik 2

### PR DESCRIPTION
**Pull request by twojstaryzdomu**
Misc improvements for Prehistorik 2:

- scrolling map
- in-game transitions
- pause screen
- quit key support
- command line toggles for DOS scrolling, Hybrid crack colours and the map
- manual palette override
- fixed some gates returning player to entry point
- fixed scrolling for non-standard window width & height
- render more sprites with larger screensize

### CODE REVIEW

**Comment by cyxx** [comment]
Nice, thanks for these!

One question regarding the palette override command line option. Is that addressing a particular issue or this is more like a debugging/experimental option to be able to start a level with a different palette?

**Comment by twojstaryzdomu** [comment]
You're welcome. The palette parameter was added for a bit of fun really. And so was the Hybrid crack look from level 4.

By the way, I noted the commit from 31st Dec fixed bears crawling over ledges and onto higher areas but broke the spiders rotation over edges (you can find those in level 1). They seem to get stuck before rotation point.

I should point out some fixes like the map are also adapted for the SDL1 version of blues, which could one day run on a classic 68k Amiga natively, which is my goal. SDL1 uses far less memory tham SDL2 (around 20M vs. 80M SDL2). Since SDL1 does not scale surfaces natively, an SDL1-based game will fit more of its tilemap in a larger window. That quirk is rather fun. So for example, the map will start scrolling from the right hand side edge, no matter what window size. The game will present a larger tilemap section. There are still some issues left to be solved with a larger window size (gates & vscroll adjust) but overall the code is fully functional in a standard 320x200 window. The SDL1 port is available in my sdl1 branch.

**Comment by cyxx** [comment]
The change 39e5eb0 may help with the spider position. I will integrate it with a next sync.

I will try to review your changes soon and merge, thanks again.

**Comment by twojstaryzdomu** [comment]
Excellent, thank you. Spiders now rotate around edges as in the original, at least when testing it briefly in level 1.

**Comment by twojstaryzdomu** [comment]
Have just added a self-explanatory parameter. You may not always want to see the map, especially when testing any in-game change.

**Comment by twojstaryzdomu** [comment]
The last commit was only refactoring object_tbl integers into macros. It had to be done to allow rendering more items with larger tilemaps in my SDL1 branch.

I came across another quirk, the paraglide in level 3 falls to ground after take off. The sprite does not resemble the paraglider sprite either.

**Comment by cyxx** [comment]
I cherry-picked some of the changes. I need to review the remaining ones, for example, `bb` and `ja` are not paused anymore when the window is not focused and valgrind reports warnings around `memmove`. I  will try to look into those.

**Comment by twojstaryzdomu** [comment]
My commits focus only on `pre2` for the time being. The pause screen is still WIP, the wording goes out of alignment in larger tilemap sizes in the SDL1 variant.

If I may ask you to cherry pick one more: the refactored `objects_tbl` hardcoded indices into macros. It will make it easier to merge your changes. All the obvious integers appearing to refer to the objects table, whether by count or offset were refactored. If any were left is likely those that don't immediately hint at being an index to the array. This commit allows to abstract from a specific sprite type range and extend it if needed, e.g. for rendering more than 20 items.

For future commits, is there any way you could break down them down into one commit, one functionality change? It makes it easier to follow (and cherry pick) what changed. Thanks.

**Comment by twojstaryzdomu** [comment]
Seeing as the `--screensize` parameter allows rendering a larger unscaled tilemap in the SDL2 variant as well, the three most recent commits address some issues present in your code. The commits depends on the large refactoring commit from earlier.

The hard limit of 20 items (`objects_tbl`-based) caused items to go missing when the item count exceeds that and raised it to 50, which appears to be good enough for a single screen (1200x700). The offset for rendering more than `22x43` tiles' worth of items has been changed to the width & height of the screen (in tiles). The limit of sprites had to be doubled to accommodate the extra sprites in a larger tilemap. One spot where I hit sprite assert from `render_add_sprite` is to the right of `--level=2 --startpos=70x30`.

The other fix is stopping scrolling right as soon as the final tile is drawn on screen (compare scrolling to end positions `--startpos=229x7 --level=0` & `--startpos=100x95 --level=1`, level 1 is unique in being 128 tiles wide). Again those fixes are mainly for `pre2`, untested in `blues` & `bbja`. A larger screensize in `blues` looks good and scrolls about right but `bbja` is mostly trashed.
With screen/window height larger than 200, gates allow for scrolling so that the larger screen isn't fixed in some weird position and for dropping down to safety to the map below.
I test the larger tilemaps with `--screensize=1200x700`. There are some funny side-effects to a larger screensize: boss fights are not rendered in the centre and pre-game screens are either too small or not scaled properly.

**Comment by twojstaryzdomu** [comment]
A small enhancement to make use of the `SELECT`/`BACK` button on a controller to quit game. Currently, it might be the only way to quit the game on some platforms (like `RPi`) where the game is run off of a tty console and a controller has been attached. It's likely the most common use case where an SDL game is started in a tty console, not an X-windows environment.

In a tty console, the keyboard input appears to be going to `stdin`, which the  `SDL_PollEvent` does not capture for some reason.

This isn't uncommon, have seen no keyboard control with other SDL games, like `SDLPoP`.

This fix will work in `blues` & `bbja` as well.

**Comment by cyxx** [comment]
Thanks. I merged some of these changes, the remaining ones can probably be specific to your fork. 

Thanks again for your contributions!

**Pull request closed without merging**
